---
id: vilma
name: Vilma
full: Domain and user administration application
description: >
  Vilma is a tool for administrators who need to handle various aspects of
  domain, user, and email administration.
list: horde
