---
id: vilma
name: Vilma
full: Domain and user administration application
description: >
  Vilma is a tool for administrators who need to handle various aspects of
  domain, user, and email administration.
list: horde
type: application
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.0.0
  api: 1.0.0
state:
  release: beta
  api: beta
license:
  identifier: BSD
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3
